### PR TITLE
RPC commands for Sidechain ledger objects and their JTX tests

### PR DESCRIPTION
**Pull request by greg7mdp**
### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by greg7mdp** [comment]
Hi Scott,

~~I thought of a pretty simple improvement, which could add significantly to the usability of the bridge. Why not allow multiple disbursement to different accounts of the funds that have been locked on the source chin and attested to by the witness server. So a wallet could batch transfers, reducing the cost per transaction.~~

implement RPC command LedgerEntry for retrieving Sidechain ledger object and some JTX Tests

PS: Please ignore the change to RippledSanity.cmake.

**Review by pwang200 — APPROVED** [review]
Good look, but clang-format might complain. 
Please consider add a couple more error test cases too.

**Comment by greg7mdp** [comment]
@pwang200 I just added a new commit to implement `RXI-290: Modify the account_history_tx_stream RPC command to add a field that returns when we reach a ledger boundary. I think @seelabs wanted you to review. I don't see a commit yet from Scott with the name updated (at least in the attest branch).

**Comment by seelabs** [comment]
merged

**Pull request closed without merging**
